const fallback='https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=80';
const cats=[['all','All'],['men','Men Clothing'],['women','Women Clothing'],['kids','Kids Clothing'],['tshirt','T-Shirts'],['shirt','Shirts'],['jeans','Jeans'],['innerwear','Innerwear'],['shoes','Shoes'],['slippers','Chappal/Slippers'],['mobile-cover','Mobile Covers'],['earbuds','Earbuds'],['headphones','Headphones'],['speaker','Speakers'],['led-light','LED Lights'],['watch','Watches'],['bag','Bags'],['charger','Chargers'],['powerbank','Power Banks'],['beauty','Beauty'],['home','Home Items']];
const demo=[{id:'p1',name:'Premium Cotton T-Shirt',category:'tshirt',price:499,oldPrice:999,rating:4.8,images:['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=80'],sizes:['S','M','L','XL'],desc:'Soft cotton regular fit t-shirt.'},{id:'p2',name:'Wireless Earbuds',category:'earbuds',price:899,oldPrice:1999,rating:4.7,images:['https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80'],sizes:['Free Size'],desc:'Bluetooth earbuds.'},{id:'p3',name:'Mobile Back Cover',category:'mobile-cover',price:199,oldPrice:499,rating:4.5,images:['https://images.unsplash.com/photo-1601972602237-8c79241e468b?auto=format&fit=crop&w=900&q=80'],sizes:['Model Wise'],desc:'Stylish mobile cover.'}];
let auth=null,db=null,currentUser=null;try{firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();auth.onAuthStateChanged(u=>{currentUser=u;loginUI();count();renderWishlist();renderOrders();adminOrders();});}catch(e){console.log('Firebase config pending',e)}
const money=n=>Number(n||0).toLocaleString('en-IN');const catName=c=>(cats.find(x=>x[0]===c)||[c,c])[1];const first=p=>(p.images&&p.images[0])||fallback;
function loginUI(){let e=document.getElementById('loginText');if(e)e.textContent=currentUser?(currentUser.displayName||currentUser.phoneNumber||'Account'):'Login'}
function googleLogin(){if(!auth)return alert('Firebase config add karo');auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())}
function phoneLogin(){if(!auth)return alert('Firebase config add karo');let ph=prompt('Mobile +91 ke sath dalo');if(!ph)return;window.recaptchaVerifier=new firebase.auth.RecaptchaVerifier('recaptcha',{size:'invisible'});auth.signInWithPhoneNumber(ph,window.recaptchaVerifier).then(c=>{let code=prompt('OTP dalo');return c.confirm(code)}).catch(e=>alert(e.message))}
async function getProducts(){let a=[...demo];if(db){let s=await db.collection('products').orderBy('createdAt','desc').get();s.forEach(d=>a.push({id:d.id,...d.data()}));}else a.push(...JSON.parse(localStorage.getItem('shoptoProducts')||'[]'));return a}
function cart(){return JSON.parse(localStorage.getItem('shoptoCart')||'[]')}function saveCart(c){localStorage.setItem('shoptoCart',JSON.stringify(c));count()}function count(){let e=document.getElementById('cartCount');if(e)e.textContent=cart().reduce((s,i)=>s+i.qty,0)}
function catLinks(){let e=document.getElementById('categoryGrid');if(e)e.innerHTML=cats.map(c=>`<a class="cat" href="products.html?cat=${c[0]}">${c[1]}</a>`).join('');let s=document.getElementById('adminCategory');if(s)s.innerHTML=cats.filter(c=>c[0]!='all').map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('')}
function card(p){return `<div class="card"><a href="product.html?id=${p.id}"><img src="${first(p)}" onerror="this.src='${fallback}'"></a><div class="body"><small style="color:#ec4899;font-weight:bold">${catName(p.category)}</small><a href="product.html?id=${p.id}"><div class="pname">${p.name}</div></a><div>⭐ ${p.rating||4.8}</div><p>${p.desc||''}</p><span class="old">₹${money(p.oldPrice)}</span><span class="new">₹${money(p.price)}</span><div class="actions"><button class="btn dark" onclick='add(${JSON.stringify(p)})'>ADD CART</button><button class="btn pink" onclick="wishlist('${p.id}')">♡ WISHLIST</button></div><a class="btn outline" style="width:100%;margin-top:8px" href="product.html?id=${p.id}">VIEW DETAILS</a></div></div>`}
function add(p,size){let c=cart();let sz=size||p.selectedSize||'';let f=c.find(i=>i.id==p.id&&i.selectedSize==sz);f?f.qty++:c.push({...p,selectedSize:sz,qty:1});saveCart(c);alert('Cart me add ho gaya')}
async function wishlist(id){if(!currentUser)return alert('Pehle login karo');await db.collection('users').doc(currentUser.uid).collection('wishlist').doc(id).set({productId:id,createdAt:Date.now()});alert('Wishlist me add ho gaya')}
async function renderWishlist(){let e=document.getElementById('wishlistList');if(!e)return;if(!currentUser||!db){e.innerHTML='<div class="note">Login karo</div>';return}let all=await getProducts();let s=await db.collection('users').doc(currentUser.uid).collection('wishlist').get();let ids=s.docs.map(d=>d.id);e.innerHTML=all.filter(p=>ids.includes(p.id)).map(card).join('')||'<div class="note">Wishlist empty</div>'}
async function loadHome(){catLinks();let e=document.getElementById('featuredGrid');if(e)e.innerHTML=(await getProducts()).slice(0,8).map(card).join('')}
async function loadProducts(){catLinks();let g=document.getElementById('productsGrid');if(!g)return;let q=(document.getElementById('searchBox')?.value||'').toLowerCase();let cat=new URLSearchParams(location.search).get('cat')||'all';let sort=document.getElementById('sortBox')?.value||'';document.getElementById('categoryTitle').textContent=catName(cat);let a=(await getProducts()).filter(p=>(cat=='all'||p.category==cat)&&(!q||(p.name+' '+p.desc+' '+catName(p.category)).toLowerCase().includes(q)));if(sort=='low')a.sort((x,y)=>x.price-y.price);if(sort=='high')a.sort((x,y)=>y.price-x.price);g.innerHTML=a.length?a.map(card).join(''):'<div class="note">No products found</div>'}
async function loadDetail(){let r=document.getElementById('productDetail');if(!r)return;let id=new URLSearchParams(location.search).get('id');let p=(await getProducts()).find(x=>x.id==id)||demo[0];let imgs=p.images||[fallback];document.body.dataset.size=(p.sizes||['Free Size'])[0];r.innerHTML=`<div class="gallery"><img class="mainimg" id="mainImg" src="${imgs[0]}" onclick="zoom(this.src)"><div class="thumbs">${imgs.slice(0,4).map((im,i)=>`<img class="${i==0?'active':''}" src="${im}" onclick="mainImg.src=this.src;document.querySelectorAll('.thumbs img').forEach(x=>x.classList.remove('active'));this.classList.add('active')">`).join('')}</div></div><div class="panel"><small style="color:#ec4899;font-weight:bold">${catName(p.category)}</small><h1>${p.name}</h1><p>⭐ ${p.rating||4.8}</p><p>${p.desc||''}</p><span class="old">₹${money(p.oldPrice)}</span><span class="new">₹${money(p.price)}</span><h3>Select Size / Variant</h3><div class="sizes">${(p.sizes||['Free Size']).map((s,i)=>`<button class="size ${i==0?'active':''}" onclick="document.body.dataset.size='${s}';document.querySelectorAll('.size').forEach(x=>x.classList.remove('active'));this.classList.add('active')">${s}</button>`).join('')}</div><h3>Size Chart</h3>${p.sizeChart?`<img class="mainimg" style="height:220px;object-fit:contain" src="${p.sizeChart}">`:'<div class="note">Size chart not uploaded.</div>'}<div class="actions"><button class="btn dark" onclick='add(${JSON.stringify(p)},document.body.dataset.size)'>Add to Cart</button><button class="btn pink" onclick='add(${JSON.stringify(p)},document.body.dataset.size);location.href="checkout.html"'>Buy Now</button></div></div>`;reviews(p.id)}
function zoom(src){zoomModal.style.display='flex';zoomModal.querySelector('img').src=src}function closeZoom(){zoomModal.style.display='none'}
function renderCart(){let e=document.getElementById('cartItems');if(!e)return;let c=cart();if(!c.length){e.innerHTML='<div class="note">Cart empty hai</div>';cartTotal.textContent='0';return}e.innerHTML=c.map((i,n)=>`<div class="row"><img src="${first(i)}"><div class="grow"><b>${i.name}</b><p>Variant: ${i.selectedSize||'-'} | ₹${money(i.price)} x ${i.qty}</p><button onclick="qty(${n},-1)">-</button> <b>${i.qty}</b> <button onclick="qty(${n},1)">+</button></div><button class="btn pink" onclick="rem(${n})">Remove</button></div>`).join('');cartTotal.textContent=money(c.reduce((s,i)=>s+i.price*i.qty,0))}
function qty(n,d){let c=cart();c[n].qty+=d;if(c[n].qty<=0)c.splice(n,1);saveCart(c);renderCart();renderCheckout()}function rem(n){let c=cart();c.splice(n,1);saveCart(c);renderCart();renderCheckout()}
function renderCheckout(){let e=document.getElementById('checkoutSummary');if(!e)return;let c=cart();e.innerHTML=c.map(i=>`<div class="row"><div><b>${i.name}</b><p>Variant: ${i.selectedSize||'-'} | ₹${money(i.price)} x ${i.qty}</p></div></div>`).join('')||'Cart empty';checkoutTotal.textContent=money(c.reduce((s,i)=>s+i.price*i.qty,0))}
function details(){return {name:customerName.value.trim(),mobile:customerMobile.value.trim(),address:customerAddress.value.trim(),pin:customerPincode.value.trim()}}function valid(d){if(!d.name||!d.mobile||!d.address){alert('Name, mobile aur address bharo');return false}return true}
async function saveOrder(o){if(db)await db.collection('orders').doc(o.id).set(o);else{let a=JSON.parse(localStorage.getItem('shoptoOrders')||'[]');a.unshift(o);localStorage.setItem('shoptoOrders',JSON.stringify(a))}}
function makeOrder(status,pay){let c=cart(),d=details();return{id:'ST'+Date.now(),uid:currentUser?currentUser.uid:'guest',customer:d,items:c,total:c.reduce((s,i)=>s+i.price*i.qty,0),status,paymentId:pay||'',returnReason:'',date:new Date().toLocaleString(),createdAt:Date.now()}}
function msg(o,type){return `🛍️ ${type} - SHOPTO\nOrder ID: ${o.id}\n${o.paymentId?'Payment ID: '+o.paymentId+'\\n':''}\n${o.items.map(i=>`${i.name} | Variant: ${i.selectedSize||'-'} | Rs.${i.price} x ${i.qty}`).join('\\n')}\n\nTotal: Rs.${o.total}\n\nCustomer: ${o.customer.name}\nMobile: ${o.customer.mobile}\nAddress: ${o.customer.address}\nPincode: ${o.customer.pin}`}
async function placeOrder(ev){ev.preventDefault();let d=details();if(!valid(d))return;let o=makeOrder('Pending','');await saveOrder(o);localStorage.removeItem('shoptoCart');location.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg(o,'CASH ON DELIVERY ORDER'))}`}
function payOnline(){let d=details(),c=cart();if(!c.length)return alert('Cart empty hai');if(!valid(d))return;if(typeof Razorpay==='undefined')return alert('Razorpay script load nahi hua');let total=c.reduce((s,i)=>s+i.price*i.qty,0);let r=new Razorpay({key:RAZORPAY_KEY_ID,amount:Math.round(total*100),currency:'INR',name:'ShopTo',description:'ShopTo Order',prefill:{name:d.name,contact:d.mobile},theme:{color:'#ec4899'},handler:async function(res){let o=makeOrder('Paid',res.razorpay_payment_id);await saveOrder(o);localStorage.removeItem('shoptoCart');alert('Payment successful. WhatsApp message open hoga, Send dabao.');location.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg(o,'PAID ORDER'))}`}});r.on('payment.failed',function(resp){alert('Payment failed: '+(resp.error.description||'Try again'))});r.open()}
async function renderOrders(){let e=document.getElementById('myOrdersList');if(!e)return;let q=(orderSearch.value||'').toLowerCase();let a=[];if(db){let s=await db.collection('orders').orderBy('createdAt','desc').get();s.forEach(d=>a.push(d.data()))}else a=JSON.parse(localStorage.getItem('shoptoOrders')||'[]');a=a.filter(o=>!q||o.id.toLowerCase().includes(q)||o.customer.mobile.includes(q));e.innerHTML=a.map(o=>`<div class="row"><div class="grow"><b>${o.id}</b> <span class="status">${o.status}</span><p>₹${money(o.total)} | ${o.customer.name}</p><small>${o.items.map(i=>i.name).join(', ')}</small>${o.returnReason?`<p><b>Return:</b> ${o.returnReason}</p>`:''}</div><button class="btn pink" onclick="ret('${o.id}')">Return Request</button></div>`).join('')||'<div class="note">No orders found</div>'}
async function ret(id){let rs=prompt('Return reason likho');if(!rs)return;if(db)await db.collection('orders').doc(id).update({status:'Return Requested',returnReason:rs});alert('Return request saved');renderOrders()}
async function admin(){catLinks();let f=document.getElementById('adminProductForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();let imgs=[adminImage1.value,adminImage2.value,adminImage3.value,adminImage4.value].filter(Boolean);let p={name:adminName.value,category:adminCategory.value,price:+adminPrice.value,oldPrice:+adminOldPrice.value,images:imgs.length?imgs:[fallback],sizes:adminSizes.value.split(',').map(x=>x.trim()).filter(Boolean),sizeChart:adminSizeChart.value,desc:adminDesc.value,rating:4.8,createdAt:Date.now()};if(db)await db.collection('products').add(p);else{let a=JSON.parse(localStorage.getItem('shoptoProducts')||'[]');a.unshift({id:'p'+Date.now(),...p});localStorage.setItem('shoptoProducts',JSON.stringify(a))}alert('Product add ho gaya');f.reset();adminProducts()};adminProducts();adminOrders()}
async function adminProducts(){let e=document.getElementById('adminProducts');if(!e)return;let all=await getProducts();e.innerHTML=all.map(p=>`<div class="row"><div class="grow"><b>${p.name}</b><p>${catName(p.category)} ₹${p.price}</p></div></div>`).join('')||'No products'}
async function adminOrders(){let e=document.getElementById('adminOrders');if(!e)return;let a=[];if(db){let s=await db.collection('orders').orderBy('createdAt','desc').get();s.forEach(d=>a.push(d.data()))}else a=JSON.parse(localStorage.getItem('shoptoOrders')||'[]');e.innerHTML=a.map(o=>`<div class="row"><div class="grow"><b>${o.id}</b><p>₹${money(o.total)} | ${o.customer.name} | ${o.customer.mobile}</p>${o.returnReason?`<p><b>Return:</b> ${o.returnReason}</p>`:''}</div><select onchange="setStatus('${o.id}',this.value)">${['Pending','Confirmed','Shipped','Delivered','Return Requested','Returned'].map(s=>`<option ${o.status==s?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')||'No orders'}
async function setStatus(id,s){if(db)await db.collection('orders').doc(id).update({status:s});adminOrders()}
function protect(){if(location.pathname.includes('admin')){let ok=sessionStorage.adminOK||prompt('Admin password:');if(ok!='1234'){alert('Wrong password');location.href='index.html'}else sessionStorage.adminOK='1234'}}
async function submitReview(){let id=new URLSearchParams(location.search).get('id'),name=reviewName.value,text=reviewText.value,photo=reviewPhoto.value,rate=reviewRating.value;if(!name||!text)return alert('Name aur feedback likho');let r={name,text,photo,rate,date:new Date().toLocaleDateString(),uid:currentUser?currentUser.uid:'guest',createdAt:Date.now()};if(db)await db.collection('products').doc(id).collection('reviews').add(r);reviews(id)}
async function reviews(id){let e=document.getElementById('reviewsList');if(!e)return;let a=[];if(db){try{let s=await db.collection('products').doc(id).collection('reviews').orderBy('createdAt','desc').get();s.forEach(d=>a.push({rid:d.id,...d.data()}))}catch(err){}}e.innerHTML=a.map(r=>`<div class="row"><div class="grow"><b>${r.name}</b> ⭐ ${r.rate}<p>${r.text}</p></div>${r.photo?`<img src="${r.photo}">`:''}</div>`).join('')||'No reviews yet'}
protect();catLinks();count();loadHome();loadProducts();loadDetail();renderCart();renderCheckout();renderOrders();admin();
