
const fallback='https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=80';
const cats=[['men','Men'],['women','Women'],['kids','Kids'],['tshirt','T-Shirts'],['shirt','Shirts'],['jeans','Jeans'],['innerwear','Innerwear'],['shoes','Shoes'],['slippers','Slippers'],['mobile-cover','Mobile Covers'],['earbuds','Earbuds'],['headphones','Headphones'],['speaker','Speakers'],['led-light','LED Lights'],['watch','Watches'],['bag','Bags'],['charger','Chargers'],['powerbank','Power Banks'],['beauty','Beauty']];
const demo=[
{id:'d1',name:'Premium Cotton T-Shirt',category:'tshirt',price:499,oldPrice:999,rating:4.8,images:['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=80'],sizes:['S','M','L','XL'],desc:'Soft cotton regular fit t-shirt.'},
{id:'d2',name:'Wireless Earbuds',category:'earbuds',price:899,oldPrice:1999,rating:4.7,images:['https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80'],sizes:['Free Size'],desc:'Bluetooth earbuds with clear sound.'},
{id:'d3',name:'Sports Shoes',category:'shoes',price:1299,oldPrice:2499,rating:4.6,images:['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'],sizes:['7','8','9','10'],desc:'Comfortable shoes for daily use.'},
{id:'d4',name:'Mobile Back Cover',category:'mobile-cover',price:199,oldPrice:499,rating:4.5,images:['https://images.unsplash.com/photo-1601972602237-8c79241e468b?auto=format&fit=crop&w=900&q=80'],sizes:['Model Wise'],desc:'Stylish protective back cover.'},
{id:'d5',name:'Bluetooth Speaker',category:'speaker',price:1199,oldPrice:2499,rating:4.6,images:['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80'],sizes:['Free Size'],desc:'Portable speaker with clear sound.'},
{id:'d6',name:'Slim Fit Formal Shirt',category:'shirt',price:799,oldPrice:1599,rating:4.7,images:['https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80'],sizes:['S','M','L','XL'],desc:'Office and party wear shirt.'},
{id:'d7',name:'Classic Denim Jeans',category:'jeans',price:1199,oldPrice:2499,rating:4.6,images:['https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80'],sizes:['30','32','34','36'],desc:'Stretchable denim jeans.'},
{id:'d8',name:'Headphones',category:'headphones',price:999,oldPrice:1999,rating:4.5,images:['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80'],sizes:['Free Size'],desc:'Over-ear headphones.'}
];
let auth=null,db=null,currentUser=null;
try{firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();auth.onAuthStateChanged(u=>{currentUser=u;ui();});}catch(e){}
const money=n=>Number(n||0).toLocaleString('en-IN'),catName=c=>(cats.find(x=>x[0]===c)||[c,c])[1],first=p=>(p.images&&p.images[0])||fallback;
function ui(){let e=document.getElementById('accountText');if(e)e.textContent=currentUser?(currentUser.displayName||currentUser.email||currentUser.phoneNumber||'Account'):'Login'}
function openLogin(){loginModal.style.display='flex'}function closeLogin(){loginModal.style.display='none'}
function googleLogin(){if(!auth)return alert('Add Firebase config first');auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()).then(closeLogin).catch(e=>alert(e.message))}
function phoneLogin(){if(!auth)return alert('Add Firebase config first');let ph=phoneInput.value.trim();if(!ph)return alert('Enter mobile number with country code');window.recaptchaVerifier=new firebase.auth.RecaptchaVerifier('recaptcha',{size:'invisible'});auth.signInWithPhoneNumber(ph,window.recaptchaVerifier).then(c=>{window.confirmResult=c;otpBox.style.display='block'}).catch(e=>alert(e.message))}
function verifyOtp(){let code=otpInput.value.trim();if(!code)return;window.confirmResult.confirm(code).then(closeLogin).catch(e=>alert(e.message))}
function allProducts(){return [...demo,...JSON.parse(localStorage.getItem('shoptoProducts')||'[]')]}
function cart(){return JSON.parse(localStorage.getItem('shoptoCart')||'[]')}function saveCart(c){localStorage.setItem('shoptoCart',JSON.stringify(c));count()}function count(){let e=document.getElementById('cartCount');if(e)e.textContent=cart().reduce((s,i)=>s+i.qty,0)}
function catBar(){let e=document.getElementById('catBar');if(e)e.innerHTML=cats.map(c=>`<a class="cat" href="products.html?cat=${c[0]}">${c[1]}</a>`).join('');let s=document.getElementById('adminCategory');if(s)s.innerHTML=cats.map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('')}
function productCard(p){return `<div class="card"><button class="heart" onclick="addWishlist('${p.id}')">♡</button><a href="product.html?id=${p.id}"><img src="${first(p)}" onerror="this.src='${fallback}'"></a><div class="body"><div class="catlabel">${catName(p.category)}</div><a href="product.html?id=${p.id}"><div class="pname">${p.name}</div></a><span class="rating">★ ${p.rating||4.5}</span><p class="desc">${p.desc||''}</p><span class="old">₹${money(p.oldPrice)}</span><span class="new">₹${money(p.price)}</span><div class="actions"><button class="btn dark" onclick='addCart(${JSON.stringify(p)})'>Add Cart</button><a class="btn pink" href="product.html?id=${p.id}">View</a></div></div></div>`}
function home(){catBar();let e=document.getElementById('featuredGrid');if(e)e.innerHTML=allProducts().slice(0,10).map(productCard).join('')}
function products(){catBar();let g=document.getElementById('productsGrid');if(!g)return;let q=(document.getElementById('searchBox')?.value||new URLSearchParams(location.search).get('q')||'').toLowerCase();let cat=new URLSearchParams(location.search).get('cat')||'all';let sort=document.getElementById('sortBox')?.value||'';let t=document.getElementById('categoryTitle');if(t)t.textContent=cat=='all'?'All Products':catName(cat);let arr=allProducts().filter(p=>(cat=='all'||p.category==cat)&&(!q||(p.name+' '+p.desc+' '+catName(p.category)).toLowerCase().includes(q)));if(sort=='low')arr.sort((a,b)=>a.price-b.price);if(sort=='high')arr.sort((a,b)=>b.price-a.price);g.innerHTML=arr.length?arr.map(productCard).join(''):'<div class="note">No products found.</div>'}
function detail(){let r=document.getElementById('productDetail');if(!r)return;let id=new URLSearchParams(location.search).get('id');let p=allProducts().find(x=>x.id==id)||demo[0];let imgs=p.images||[fallback];document.body.dataset.size=(p.sizes||['Free Size'])[0];r.innerHTML=`<div class="gallery"><img class="mainimg" id="mainImg" src="${imgs[0]}" onclick="zoom(this.src)" onerror="this.src='${fallback}'"><div class="thumbs">${imgs.slice(0,4).map((im,i)=>`<img class="${i==0?'active':''}" src="${im}" onclick="mainImg.src=this.src;document.querySelectorAll('.thumbs img').forEach(x=>x.classList.remove('active'));this.classList.add('active')" onerror="this.src='${fallback}'">`).join('')}</div><p class="note">Click image to zoom.</p></div><div class="panel"><div class="catlabel">${catName(p.category)}</div><h1>${p.name}</h1><span class="rating">★ ${p.rating||4.5}</span><p>${p.desc||''}</p><span class="old">₹${money(p.oldPrice)}</span><span class="new">₹${money(p.price)}</span><h3>Select Size / Variant</h3><div class="sizes">${(p.sizes||['Free Size']).map((s,i)=>`<button class="size ${i==0?'active':''}" onclick="document.body.dataset.size='${s}';document.querySelectorAll('.size').forEach(x=>x.classList.remove('active'));this.classList.add('active')">${s}</button>`).join('')}</div><h3>Size Chart</h3>${p.sizeChart?`<img class="mainimg" style="height:220px;object-fit:contain" src="${p.sizeChart}">`:'<div class="note">Size chart not uploaded.</div>'}<div class="actions"><button class="btn dark" onclick='addCart(${JSON.stringify(p)},document.body.dataset.size)'>Add Cart</button><button class="btn pink" onclick='addCart(${JSON.stringify(p)},document.body.dataset.size);location.href="checkout.html"'>Buy Now</button></div></div>`;reviews(p.id)}
function zoom(src){zoomModal.style.display='flex';zoomModal.querySelector('img').src=src}function closeZoom(){zoomModal.style.display='none'}
function addCart(p,size){let c=cart(),sz=size||p.selectedSize||'';let f=c.find(i=>i.id==p.id&&i.selectedSize==sz);f?f.qty++:c.push({...p,selectedSize:sz,qty:1});saveCart(c);alert('Added to cart')}
async function addWishlist(id){if(!currentUser||!db){openLogin();return}await db.collection('users').doc(currentUser.uid).collection('wishlist').doc(id).set({productId:id,createdAt:Date.now()});alert('Added to wishlist')}
function renderWishlist(){let e=document.getElementById('wishlistList');if(e)e.innerHTML='<div class="note">Login and Firebase config required for permanent wishlist.</div>'}
function renderCart(){let e=document.getElementById('cartItems');if(!e)return;let c=cart();if(!c.length){e.innerHTML='<div class="note">Your cart is empty.</div>';cartTotal.textContent='0';return}e.innerHTML=c.map((i,n)=>`<div class="row"><img src="${first(i)}"><div class="grow"><b>${i.name}</b><p>Variant: ${i.selectedSize||'-'} | ₹${money(i.price)} x ${i.qty}</p><button onclick="qty(${n},-1)">-</button> <b>${i.qty}</b> <button onclick="qty(${n},1)">+</button></div><button class="btn pink" onclick="rem(${n})">Remove</button></div>`).join('');cartTotal.textContent=money(c.reduce((s,i)=>s+i.price*i.qty,0))}
function qty(n,d){let c=cart();c[n].qty+=d;if(c[n].qty<=0)c.splice(n,1);saveCart(c);renderCart();renderCheckout()}function rem(n){let c=cart();c.splice(n,1);saveCart(c);renderCart();renderCheckout()}
function renderCheckout(){let e=document.getElementById('checkoutSummary');if(!e)return;let c=cart();e.innerHTML=c.map(i=>`<div class="row"><div><b>${i.name}</b><p>Variant: ${i.selectedSize||'-'} | ₹${money(i.price)} x ${i.qty}</p></div></div>`).join('')||'Cart is empty';checkoutTotal.textContent=money(c.reduce((s,i)=>s+i.price*i.qty,0))}
function dets(){return{name:customerName.value.trim(),mobile:customerMobile.value.trim(),address:customerAddress.value.trim(),pin:customerPincode.value.trim()}}function valid(d){if(!d.name||!d.mobile||!d.address){alert('Please enter name, mobile and address');return false}return true}
function saveOrder(o){let a=JSON.parse(localStorage.getItem('shoptoOrders')||'[]');a.unshift(o);localStorage.setItem('shoptoOrders',JSON.stringify(a))}
function makeOrder(status,pay){let c=cart(),d=dets();return{id:'ST'+Date.now(),customer:d,items:c,total:c.reduce((s,i)=>s+i.price*i.qty,0),status,paymentId:pay||'',returnReason:'',date:new Date().toLocaleString()}}
function message(o,type){return `🛍️ ${type} - SHOPTO\nOrder ID: ${o.id}\n${o.paymentId?'Payment ID: '+o.paymentId+'\\n':''}\n${o.items.map(i=>`${i.name} | Variant: ${i.selectedSize||'-'} | Rs.${i.price} x ${i.qty}`).join('\\n')}\n\nTotal: Rs.${o.total}\n\nCustomer: ${o.customer.name}\nMobile: ${o.customer.mobile}\nAddress: ${o.customer.address}\nPincode: ${o.customer.pin}`}
function placeOrder(ev){ev.preventDefault();let d=dets();if(!valid(d))return;let o=makeOrder('Pending','');saveOrder(o);localStorage.removeItem('shoptoCart');location.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message(o,'CASH ON DELIVERY ORDER'))}`}
function payOnline(){let d=dets(),c=cart();if(!c.length)return alert('Cart is empty');if(!valid(d))return;if(typeof Razorpay==='undefined')return alert('Razorpay not loaded');let total=c.reduce((s,i)=>s+i.price*i.qty,0);let r=new Razorpay({key:RAZORPAY_KEY_ID,amount:Math.round(total*100),currency:'INR',name:'ShopTo',description:'ShopTo Order',prefill:{name:d.name,contact:d.mobile},theme:{color:'#ec4899'},handler:function(res){let o=makeOrder('Paid',res.razorpay_payment_id);saveOrder(o);localStorage.removeItem('shoptoCart');alert('Payment successful. WhatsApp will open. Please tap Send.');location.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message(o,'PAID ORDER'))}`}});r.open()}
function renderOrders(){let e=document.getElementById('myOrdersList');if(!e)return;let q=(orderSearch.value||'').toLowerCase();let arr=JSON.parse(localStorage.getItem('shoptoOrders')||'[]').filter(o=>!q||o.id.toLowerCase().includes(q)||o.customer.mobile.includes(q));e.innerHTML=arr.map(o=>`<div class="row"><div class="grow"><b>${o.id}</b><p>₹${money(o.total)} | ${o.customer.name}</p>${o.returnReason?`<p><b>Return:</b> ${o.returnReason}</p>`:''}</div><button class="btn pink" onclick="ret('${o.id}')">Return Request</button></div>`).join('')||'<div class="note">No orders found.</div>'}
function ret(id){let reason=prompt('Enter return reason');if(!reason)return;let a=JSON.parse(localStorage.getItem('shoptoOrders')||'[]');let o=a.find(x=>x.id==id);if(o){o.status='Return Requested';o.returnReason=reason;localStorage.setItem('shoptoOrders',JSON.stringify(a));renderOrders()}}
function admin(){catBar();let f=document.getElementById('adminProductForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();let imgs=[adminImage1.value,adminImage2.value,adminImage3.value,adminImage4.value].filter(Boolean);let p={id:'p'+Date.now(),name:adminName.value,category:adminCategory.value,price:+adminPrice.value,oldPrice:+adminOldPrice.value,images:imgs.length?imgs:[fallback],sizes:adminSizes.value.split(',').map(x=>x.trim()).filter(Boolean),sizeChart:adminSizeChart.value,desc:adminDesc.value,rating:4.8};let a=JSON.parse(localStorage.getItem('shoptoProducts')||'[]');a.unshift(p);localStorage.setItem('shoptoProducts',JSON.stringify(a));alert('Product added');f.reset();adminProducts()};adminProducts();adminOrders()}
function adminProducts(){let e=document.getElementById('adminProducts');if(e)e.innerHTML=allProducts().map(p=>`<div class="row"><div class="grow"><b>${p.name}</b><p>${catName(p.category)} | ₹${p.price}</p></div></div>`).join('')}
function adminOrders(){let e=document.getElementById('adminOrders');if(e)e.innerHTML=JSON.parse(localStorage.getItem('shoptoOrders')||'[]').map(o=>`<div class="row"><div class="grow"><b>${o.id}</b><p>₹${money(o.total)} | ${o.customer.name}</p></div></div>`).join('')||'No orders'}
function protect(){if(location.pathname.includes('admin')){let ok=sessionStorage.adminOK||prompt('Admin password:');if(ok!='1234'){alert('Wrong password');location.href='index.html'}else sessionStorage.adminOK='1234'}}
function submitReview(){alert('Feedback submitted. Firebase config required to save publicly.')}
function reviews(id){let e=document.getElementById('reviewsList');if(e)e.innerHTML='No reviews yet.'}
protect();catBar();count();home();products();detail();renderCart();renderCheckout();renderOrders();renderWishlist();admin();
